### ISSUE TITLE
Не компилируется

### ISSUE THREAD

**Issue by teuchezh** [vvip-68/GyverMatrixWiFi#1]
[Скрин](https://imgur.com/qhs41Js)

**Comment by aka-inc** [comment]
Нужно выбрать в менеджере плат WeMos D1 R2. Под неё у меня компилируется.

**Comment by teuchezh** [comment]
> Нужно выбрать в менеджере плат WeMos D1 R2. Под неё у меня компилируется.

А на что заливаешь? NodeMCU или WeMos?

**Comment by aka-inc** [comment]
на голую ESP8266-12E с 1Мб памяти. Микроконтроллер на этих платах один и тот же, отличается наличием дополнительных резисторов, USB-TTL и прочим обвесом. Если компилирую под Generic ESP8266 или NodeMCU, то тоже не компилируется. На более ранних версиях были ошибки в функциях работы с кнопками и блютуз, я ошибки исправлял, и всё компилировалось под любые платы ESP8266.

**Comment by teuchezh** [comment]
> на голую ESP8266-12E с 1Мб памяти. Микроконтроллер на этих платах один и тот же, отличается наличием дополнительных резисторов, USB-TTL и прочим обвесом. Если компилирую под Generic ESP8266 или NodeMCU, то тоже не компилируется. На более ранних версиях были ошибки в функциях работы с кнопками и блютуз, я ошибки исправлял, и всё компилировалось под любые платы ESP8266.

Скомпилировал под WeMos, все работает отлично, спасибо за совет

**Comment by vvip-68** [comment]
В копилку опыта...
