### ISSUE TITLE
Картинка сбрасывается после таймаута

### ISSUE THREAD

**Issue by khvalov** [vvip-68/GyverMatrixWiFi#10]
В режиме загрузки картинки - по истечении таймаута программа переходит обратно в демо режим. ИМХО было бы логично сохранять картинку или до сброса или до принудительного перевода экрана в режим отличный от картинки (например если хочешь отображать логотип до тех пор пока не сбросишь его)

**Comment by vvip-68** [comment]
Отключение автоперехода в демо режим не решает ситуацию?
Так то судя по описанию - всё работает как и задумывалось.

**Comment by khvalov** [comment]
С автопереходом я попробую поиграться, но полное отключение демо режима не решает проблему. В НЕ-Демо режиме черех (примерно) 5 минут программа переходит в режим отображения времени

**Comment by vvip-68** [comment]
Что стоит в приложении в поле "Авторежим через xxx минут"?
Если xxx - 0 - он не должен автоматически переходить в демо-режим. Должен оставаться последний включенный вручную режим, в т.ч. - загруженная картинка

**Comment by khvalov** [comment]
Попробуйю сегодня и отпишусь

**Comment by vvip-68** [comment]
Я попробовал. У меня загруженная картинка два часа простояла, пока я режим не сменил.
