### ISSUE TITLE
Не могу разобраться, не работают 3 эффекта

### ISSUE THREAD

**Issue by Evgeny161rus** [vvip-68/GyverMatrixWiFi#12]
При выборе в приложении эффектов "Дыхание", "Цвета" и "Радуга Пикс" Картинка на матрице виснет, так же, чекбоксы "Часы поверх эффекта" и "Использовать в Демо-режиме" становятся неактивными. При выборе любого другого эффекта всё работает. Node Mcu менял, прошивал разными прошивками, и от Gyvera, и этой, эффекта ноль, приложение переустанавливал. Что я делаю не так?

**Comment by vvip-68** [comment]
Всё так. Эти "эффекты" - на самом деле не эффекты формирования картинки на матрице как остальные, а нечто специфическое, что работает практически только для бегущей строки (и, возможно, в режиме рисования) - эффект трансформации существующего отображения. При их включении в бегущей строке (в нарисованной картинке) она плавно пульсирует яркостью или меняет свой цвет по радуге. Из за их специфичности недоступны галочки "Использовать" и "Часы". Остались рудиментом от самой первой версии матрицы от Гайвера. По хорошему их (эти три эффекта) вообще надо либо выкинуть либо перенести на страничку Текста. Но переделывать уже как-то лень. Времени потратить нужно много, а "выхлопа" с этого - чуть.

**Comment by Evgeny161rus** [comment]
Вот да, если бы их перенести на страничку текста, было бы идеально. Я не гуру в программировании, поэтому не осилю
