### ISSUE TITLE
Can you translate these fields of aia file into english for us?

### ISSUE THREAD

**Issue by tihoangyeudau** [vvip-68/GyverMatrixWiFi#13]
I cant change these fields of aia file into english https://i.imgur.com/6jrF2kT.jpg https://i.imgur.com/sT5VTZD.jpg 

Can u help me? Using it by russian make me difficult to use.

**Comment by vvip-68** [comment]
Настройки - Settings
Подключить - Connect

Do not hesitate to ask about another element translations.
Note, lists of effects, alarms and games are coming from sketch and must be translated in sketch.
Lines 119-121 of main sketch file

**Comment by tihoangyeudau** [comment]
Thank you i can do it.
