### ISSUE TITLE
Проблема с приложением android

### ISSUE THREAD

**Issue by Kenaed** [vvip-68/GyverMatrixWiFi#14]
1. В приложении если при работе с рисовалкой из неё выйти и снова войти все ячейки пустые, но продолжается рисование как будто они заполнены 

2. Идея модернизации: сделать в рисовалке кнопку получить код, чтоб то что нарисовано получить в виде кода, и желательно в том же виде, который вставляется во вкладке анимация, и кнопку вставить код. Это позволит хранить и не перерисовывать одни и те же рисунки.

**Comment by vvip-68** [comment]
А если ты вышел из рисовалки, включил какой-то эффект, все нарисованное на матрице стерлось/поменялось, а потом ты вернулся обратно в рисовалку. Что по твоему должно быть в приложении в поле рисования? ИМХО этот сценарий гораздо более частый, поэтому при включении в программе страницы "Рисование" имеем черный экран.

Впрочем - исходники открытые. Ты можешь написать спец-протокол, по которому программа будет запрашивать матрицу что она светит и в программе это же отображать. Хотя, если изображение все время меняется - в программе ты все равно получишь неактуальное.

По модернизации - код открытый. В т.ч. и приложения. Пиши хотелки под себя. Как напишешь рабочую версию - делай Pull request. Если все работать будет - включу в проект.

**Comment by Kenaed** [comment]
захожу во вкладку рисование, рисую, перехожу в настройки (не меняя режима) возвращаюсь в рисование и происходит то что я написал, добавь хоть чтоб поле если чистое при заходе и матрица чистилась

**Comment by vvip-68** [comment]
Это не предусмотрено специально еще с версии, написанной Гайвером. И я в этом плане ничего переделывать не стал. Не чистится, потому что играя, например в змейку или во что там еще - можно поставить паузу, переключиться в режим рисования и нарисовать дополнительные препятствия. Или Нарисовав рисунок переключиться в эффекты и включить цветовые эффекты типа "Дыхание" или Радуга пикс.
В общем всё работает именно так как задумывалось изначальным автором и это не баг, это фича. Лично мне это не мешает и тратить время на такого типа хотелки я не стану.
Код открытый. Возьми и сделай как тебе нужно всё под себя.

**Comment by Kenaed** [comment]
можешь тогда подсказать в каком месте ведется передача данных в контроллер?

**Comment by vvip-68** [comment]
блок-процедура sendText

**Comment by Kenaed** [comment]
благодарю
