### ISSUE TITLE
Скорость игр в демо-режиме

### ISSUE THREAD

**Issue by ghost** [vvip-68/GyverMatrixWiFi#15]
Уважаемый **vvip-68**, не могли бы проверить такой момент: выбираю каждую из игр, настраиваю скорость - минимальную. Но когда выбираю режим "демо", то скорость возрастает на максимум или почти на максимум. Только в играх. Если снова захожу в игры - скорость стоит в минимуме. В остальных эффектах скорость сохраняется такой, какую выбрал (опять же минимум, например) и самопроизвольно не меняется.

**Comment by vvip-68** [comment]
Ну так то скорость игр в демо режиме постоянна и задается константой в скетче, а скорость игры настраиваемая - действует только в ручном режиме. То есть - они не связаны.
Ну хорошо, изменил скетч так, чтобы в демо-режиме игры отображались с той же скоростью, что была задана в настройках. Обновил скетч в репозитории. Попробуйте, отпишитесь что получилось.

**Comment by ghost** [comment]
Спасибо большое, все работает. Скорость игр в демо остаётся как выбрал в настройках
