### ISSUE TITLE
Приложение не конектитса никак

### ISSUE THREAD

**Issue by NazarDoeH** [vvip-68/GyverMatrixWiFi#17]
Я сделал матрицу без датчика свіета и проигривателя сначала она нивкакую нехотела пото часов в 12 ночи я смог подключитса через ее точку доступа потом като (сам хз как) и по вайфаю 
но ето било не долог всеволиш неделю теперь она опять нивкакую нехочет конектитма 
помоги я незнаю штоделать

**Comment by vvip-68** [comment]
Ну, если неделю работало, потом перестало, значит дело не в прошивке (прошивка то та же самая), а в аппаратной части. Например в телефоне. Похоже у него какие-то проблемы. Что за телефон? Подключается ли с другого телефона? Подключается ли телефон к точке доступа? Есть ли эта точка доступа? Стабильное ли питание на микроконтроллере? Может блок питания в другую розетку воткнули - помехи пошли? Что пишет в мониторе порта? Вопросов - миллион.

**Comment by NazarDoeH** [comment]
Телефон Xiaomi redmi note 4 .С другова непробивал.К самой точке подключаетса но ненадолго она потом одключаетса хотя сам модуль подключаетса к вайфаю и мает свой Айпи.Питание вроде норм ~5.10В подключил через стандартний бп.Нет Он стоял в одной и тойже розетке.Монитор порта пишит о подключении к вайфаю и айпи в нем ну и порт дальше он синхронитса з сервером но через какоето время он какби из еерома загружаетса но результат тотже

**Comment by vvip-68** [comment]
Вот попробуйте все же с другого телефона. На стене были обсуждения, что точка падает, когда к ней с телефонов Xiaomi подключаются. Есть подозрение, что у этих телефонов как-то не совсем корректно реализован стек WiFi, и при несоблюдении протокола связи у ESP-шки просто сносит крышу и WiFi в ней падает до перезагрузки практически...

**Comment by NazarDoeH** [comment]
И как ето решить у меня Мой телефон то Xiaomi уменя есть канешно и другие но они не мои

**Comment by vvip-68** [comment]
Ну для начала попробовать - действительно ли это так.

**Comment by NazarDoeH** [comment]
Ок спасибо попробою напишу
