### ISSUE TITLE
speed of text is not working

### ISSUE THREAD

**Issue by tihoangyeudau** [vvip-68/GyverMatrixWiFi#18]
When I was in the text section, I dragged the speed bar of the text to the right so the word didn't run faster.

Пейнтбол effect is can not be adjusted speed

When I turned off or turned on the demo mode, the wifi ip of led was disconnected and then not reconnected. But this error must be carefully tested so you can only see it appear

**Comment by vvip-68** [comment]
Ok, thank you for report.
Speed text issue fixed on comment 10.11.2019 (last comment on this moment).
However I update esp8266 core on latest 2.6 version. 
This version changed SerialSoftware class and changes are not compatible with usage SoftwareSerial in sketch. I tried to change it, but not sucesfully yet - matrich couldn`t read MP3 player and report that it is absent :( Continue working on it.

Regarding speed settings for Пейнтбол (Paintball) effect. Effect is suggested by one of user. Implementation has not settings for this effect, it running on maxiamal speed. I managed to implement speed regulation, but not sucessfully. Used functions hardly depend on real time timers - beat8sin() of FastLed library. Attempt to tune speed lead to drawing effect not smoothly.
So, I couldnt implement settings for speed. Currently speed trackbar do select variation of effect - 1,2,3 or 4 balls moving over the screen. Probably speed regulation i will implement at next attempts.

Didn`t understand about last issue with connection.
However I discovered that A0 analog input is internally used by WiFi part of MCU for some internal meassures. So, If you are not physically have photoresistor connected to A0, call of analogRead() may cause tamper internal usage of WiFi measure and MCU may turn off WiFi. 
In the last version of sketch I added definition for USE_PHOTO constant. If you does not have photoresistor, set USE_PHOTO to 0. This will avoid use analogRead() part of code that may protect WiFi from crash
