### ISSUE TITLE
Добавление цветомузыки и управления от микрофона

### ISSUE THREAD

**Issue by aka-inc** [vvip-68/GyverMatrixWiFi#2]
Есть ли возможность прикрутить эффект цветомузыки? Через микрофон (LineOut) на единственный аналоговый вход ESP8266. Также можно выключать будильник хлопком в ладоши.. или включать следующий режим эффектов двойным хлопком.

Спаял матрицу 15х20 размером 3,8х3,5 метра на весь потолок на микроконтроллере ESP8266-12E, который разместил внутри блока питания 5В 20А. Чтобы избавиться от наводок и глюков, использовал коаксиальный кабель на DIN светодиодной ленты, ферритовое кольцо на линии питания контроллера, обвязку из конденсаторов, а также пришлось понизить напряжение на светодиодах до 4.4В. Причём на ардуине с её питанием 5В глюки на матрице большого размера тоже налюдаются, если не понизить напряжение до 4.4В. Глюки проявляются на контрастных режимах с резким переключением яркости диодов, и добавление конденсатора в линию питания контроллера и ленты ничего не даёт. А при пониженном напряжении ничего не глючит, нет спонтанных вспышек и артефактов, но яркость сильно ниже, и цветовой спектр диодов становится очень узкий. Увличение расстояния контроллера от блока питания и его экранирование фольгой не влияют на глюки. Они явно связаны с рассогласованием уровней сигнала контроллера и питания.

**Comment by vvip-68** [comment]
Ну, я этим заниматься не буду. Мне это направление не интересно. Если сделаете и это будет работать - включим код в проект... К тому же единственный аналоговый вход ESP8266 уже занят под фоторезистор для автоматической корректировки яркости в зависимости от освещенности.
Для маленьких матриц (типа 16x16) больше, видимо, дописывать ничего не предвидится.
Когда соберу большую настенную размерами примерно 30х40 - посмотрю как будет работать и, видимо немного допишу чего-нибудь в плене отображения. Например часы бОльшим шрифтом, расстояние между цифрами большее, чтоб точки не сливались, может быть "гуляние" часов по экрану, отображение вместе с датой...
