### ISSUE TITLE
Зеркальное отображение

### ISSUE THREAD

**Issue by iamlexs** [vvip-68/GyverMatrixWiFi#20]
Хотелось бы реализацию настройки в приложении для зеркального отображения. 
Например, если есть гирлянда в окне, чтобы можно было развернуть изображение наружу или внутрь.

**Comment by vvip-68** [comment]
Это все регулируется настройками угла подключения и направления ленты
Также, возможно, что-то получится с текстом, если поиграться настройками
#define MIRR_V 0          // отразить текст по вертикали (0 / 1)
#define MIRR_H 0          // отразить текст по горизонтали (0 / 1)
в runningText.ino

**Comment by iamlexs** [comment]
Про настройки прошивки все понятно.
Я имел ввиду зеркалирование во время работы устройства.
Сейчас же надо перепрошивать контроллер.
Добавить всего 1 чекбокс в приложение :)
