### ISSUE TITLE
narodmon

### ISSUE THREAD

**Issue by NLObP** [vvip-68/GyverMatrixWiFi#22]
Привет vvip-68! Помоги добавить в бегущую строку температуру с сайта narodmon.ru. У них в справке есть описание как добавить в приложения, на сайт... У меня есть кое-какие наброски, не получается внедрить. Нули показывает, так-как текст для строк пишется в setup.

**Comment by vvip-68** [comment]
Я на заказ не делаю. Это тебе или самому разбираться - тем более все расписано, говоришь. Или в "ищу разработчика". 
Текст для строк можно менять в любой момент в программе, где тебе нужно.
