### ISSUE TITLE
Проблема направлением бегущей строки текста при отзеркаливании

### ISSUE THREAD

**Issue by ameth-cmd** [vvip-68/GyverMatrixWiFi#23]
Столкнулся с такой проблемой:

Собираю матрицу "на окне", "лицом" к себе, т.е. говоря словами прошивки -

#define MATRIX_TYPE 0​
#define CONNECTION_ANGLE 0​
#define STRIP_DIRECTION 1​
Сама матрица нанесена на окно с его левого нижнего угла в правый и далее зигзагом.

Т.е. вот так: https://prnt.sc/qa4dg9

По-умолчанию, текст выводится так, чтобы его было видно "из квартиры", т.е. стоя "лицом" к матрице.
Бегущая строка при этом идет из правого угла в левый, буквы в "нормальном" виде, т.е. глядя из кваритры - все ок, глядя из улицы - текст "отзеркален" и идет "не в ту сторону".

Т.е. вид изнутри квартиры: http://prntscr.com/qa4dml

Вид с улицы: http://prntscr.com/qa4dqc

В настройках прошивки конечно же есть параметр

#define MIRR_V 1 - и в таком случае буквы "отзеркаливаются" и их видно "правильными" со стороны улицы.

Но направление текста при этом не меняется, и с точки зрения зрителя с улицы оно идет из левого угла в правый, хоть и буквы
при этом выглядят правильно.

 Т.е. вот так: http://prntscr.com/qa4dtg

Можно ли как-то поменять направление текста, чтобы он шел "из правого угла в левый" для зрителя из улицы, т.е. того, к которому матрица повернута "изнанкой"?

**Comment by vvip-68** [comment]
Не надо ничего делать с MIRR_V 1 Это не для этого. Это именно для отражения в зеркале.
Чтобы бегущая строка правильно читалась с улицы - задайте правильно угол подключения и направление матрицы. То есть не с точки зрения как оно смотрится из квартиры, а так, как вы бы смотрели на матрицу с улицы.  В вашем случае это будет
направление с его правого нижнего угла в левый и далее зигзагом.
