### ISSUE TITLE
TimeZone need edit 2 times (2 different places)

### ISSUE THREAD

**Issue by AlexxVel** [vvip-68/GyverMatrixWiFi#24]
У меня телефон с Android 4.2  Установить на него приложение GyverMatrixWiFi.apk я не могу (т.к. там минимальная версия API 19, т.е. Android 4.4). Из-за невозможности установить и использовать приложение, столкнулся с проблемой неправильного вывода времени на матрицу (виновница - timeZoneOffset). Как оказалось - недостаточно только отредактировать строку 453 в файле GyverMatrixOS_v1.15.ino:  int8_t timeZoneOffset = 3;  (выставить свою таймзону).
необходимо также отредактировать строку 168 в eeprom.ino :
timeZoneOffset = 3;
Что несколько неудобно (и начинающие пользователи, не разбирающиеся в коде, будут в затруднительном положении...)

**Comment by vvip-68** [comment]
Да, спасибо. Убрал из eeprom.ino
