### ISSUE TITLE
Ntp сервер, что я делаю не так

### ISSUE THREAD

**Issue by igorpats** [vvip-68/GyverMatrixWiFi#25]
Никак не могу настроить синхронизацию с ntp сервером. Проблема в следующем:
22:36:02.254 -> NTP-сервер www.belgim.by -> 178.124.164.107
22:36:02.254 -> Отправка NTP пакета на сервер www.belgim.by
22:36:07.075 -> UDP пакeт размером 6 от 192.168.1.218, порт 2390
22:36:07.075 -> Содержимое: $18 0;
22:36:07.244 -> Таймаут NTP запроса!
И так постоянно какой-бы адрес не указывал. Не могу понять почему оно пакеты не принимает от сервера. Порт использовал 123 как в исходнике. Пробовал и другие.

**Comment by vvip-68** [comment]
Скорее всего у вас на роутере или у провайдера закрыт 123 порт и пакеты запроса к серверу не уходят. Что, например, говорит Windows при попытке синхронизировать его время с сервером ntp? Можно поискать для теста стороннюю программу на комп - синхронизатор времени NTP. Работает ли он? Что сообщает?
Другие порты использовать бесполезно. 123 порт - стандартный порт сервиса синхронизации времени. Если сервера времени специально админы на другой порт не переносят. А такого практически не бывает, ибо стандарт.
Проверьте работу синхронизации времени на компе. Если в вашей сети она не работает (заблокирована) - смотрите нет ли запрета в настройках роутера и/или пишите письмо админу, пусть разбирается.

**Comment by igorpats** [comment]
Windows 7 на вкладке синхронизация времени по интернету делает это без вопросов с любым рабочим сервером. Вот к примеру использовал стороннюю ntpquerty и в бил туда ip из вашего списка.
![image](https://user-images.githubusercontent.com/59146149/71396335-b5468100-262a-11ea-99ee-c8e83afbb8e1.png)  Пытался смотреть переменные через монитор порта, никогда не получаю ничего в ответ на запрос.

**Comment by vvip-68** [comment]
Ну, тогда у меня нет ответа. Вы единственный из сотен собравших у кого это не работает.
Если найдете, что причина все же в скетче - сообщите, исправим. По логике кода я проблем не вижу. Повторить ошибку  не могу. Исправить, следовательно, тоже. С моей точки зрения там нечему не работать.

**Comment by igorpats** [comment]
Вот странно, прошу людей скинуть лог с монитора порта, где видно что работает, так никто и не может. Я бы и сам не полез если бы затыков не было после определенной серии неудачных подключений (wifi переподключает).  Попробую прошивку с лампы с готовой библиотекой ntp запустить и посмотреть что происходит.

**Comment by vvip-68** [comment]
Ну, вот что выводит сразу при включении:
18:21:43.358 -> ....
18:21:45.669 -> WiFi подключен. IP адрес: 192.168.0.96
18:21:45.703 -> 
18:21:45.703 -> UDP-сервер на порту 2390
18:21:45.703 -> Инициализация MP3 плеера...
18:21:46.151 -> Звуков будильника найдено: 2
18:21:46.151 -> Звуков рассвета найдено: 6
18:21:46.151 -> Включен эффект 'Радужные переливы'
18:21:46.151 -> NTP-сервер ru.pool.ntp.org -> 192.36.143.130
18:21:46.151 -> Отправка NTP пакета на сервер ru.pool.ntp.org
18:21:46.252 -> UDP пакeт размером 48 от 192.36.143.130, порт 123
18:21:46.252 -> Разбор пакета NTP
18:21:46.252 -> Секунд с 1970: 1577211705

Так если мешает перезагрузка сети при 10 неудачных попытках синхронизации - просто убери эту строчку из скетча.

Ты часом скетч не редактировал? Может удалил кусок, где данные от сервера принимаются и парсятся?

**Comment by igorpats** [comment]
нет, не редактировал. Специально из архива вытаскивал и менял перед опытами. А никаких изменений не вносилось с предыдущих версий. Я просто не помню раньше затыков при включенной синхронизации с ntp. Можно просто в режиме точки доступа использовать для управления. 
Попробую сегодня покрутить настройки роутера по поводу 123 порта.

**Comment by vvip-68** [comment]
Постоянно что-то вносится в версии. На то и смена. Но касательно именно работы с NTP не менялось ничего. Как в версии 1.12 было - так все и осталось. Если тебе не нужна синхронизация (или она вот так вот не работает) - просто выключи ее из приложения - там галочка есть "Использовать синхронизацию с NTP" в настройках часов.

**Comment by igorpats** [comment]
Спасибо, так и делал. Для примера поставил последнюю прошивку с лампы, там библиотека ntp есть. Добавил вывод времени в 
![2019-12-24_20-19-20](https://user-images.githubusercontent.com/59146149/71421292-fff7e580-268a-11ea-8164-51e7b9dd3e7b.png)
порт, показывает корректно, значит оно работает.

**Comment by igorpats** [comment]
Поставил голую прошивку только поменял ssid и пароль сети и залил. Ничего не трогал вообще
![2019-12-24_20-39-15](https://user-images.githubusercontent.com/59146149/71421731-cc6a8a80-268d-11ea-959d-d4ba7e1eaef9.png) Тоже самое. Версия ядра 2.6.1

**Comment by igorpats** [comment]
Что-то мне кажется что это с портами связанно. У моего провайдера динамический ip, спрятанный за natoм. Вариантов получить белый ip почти нет. Буду побывать долбить их.

**Comment by vvip-68** [comment]
Вряд ли с портами. 123 порт - стандарт для NTP; 
У меня тоже не белый IP - но работает же почему-то.
Или нет? Затык может быть в строчке (которая на прежних ядрах точно работала!)
WiFi.hostByName(ntpServerName, timeServerIP);
Потому что IP по которому идет запрос - 192.36.143.130 - аварийный, когда не удается преобразовать имя хоста в IP. Но у меня этот IP откликается, а у вас видимо нет.
Когда оно работало - получался каждый раз разный IP сервера из их пула.
Попробуйте хотя бы на компе несколько раз подряд выполнить ping ru.pool.ntp.org
Каждый раз практически разные IP выдаются. И точно не этот "аварийный". А тут всегда аварийный используется...
Надо посмотреть внимательнее этот момент...
Пропишите вместо этого аварийного другой, который у вас точно откликается, с которым вам удалось время синхронизировать.

**Comment by igorpats** [comment]
![2019-12-25_12-33-41](https://user-images.githubusercontent.com/59146149/71441540-e8643f80-2712-11ea-82bd-1a9f0c666698.png)
Пингуется всегда с одним адресом
Вот если вбить просто pool.ntp.org
![2019-12-25_12-36-58](https://user-images.githubusercontent.com/59146149/71441724-b7d0d580-2713-11ea-9b27-74d4fe285ba6.png)
Уже другой адрес что естественно.
Ниже фото что win синхронизирует время с обоими серверами
![2019-12-25_12-36-58](https://user-images.githubusercontent.com/59146149/71441756-e5b61a00-2713-11ea-8b88-7dde087e537f.png)
![2019-12-25_12-37-14](https://user-images.githubusercontent.com/59146149/71441761-e8b10a80-2713-11ea-9503-e132564679f6.png)
Просто по 123 порту ничего не идет, и в DMZ добавлял свой ip. Глухо
![2019-12-25_12-38-04](https://user-images.githubusercontent.com/59146149/71441808-1eee8a00-2714-11ea-8c4b-02624dad6e74.png)

**Comment by igorpats** [comment]
Делаю тоже самое через 123 порт:
![2019-12-25_12-46-53](https://user-images.githubusercontent.com/59146149/71441944-be138180-2714-11ea-97e8-5658c72ce57b.png)

**Comment by igorpats** [comment]
Порт закрыт, любой адрес через 123 не откликается

**Comment by vvip-68** [comment]
Я бы не стал верить винде, что она синхронизировалась. Те еще пройдохи.
Как она синхронизируется? Не через 123 порт? У нее свое что-то?
Ну если 123 порт закрыт (где? На роутере? у провайдера?) так синхронизация и не будет работать... Провайдеру письмо написать - что ответит?

**Comment by igorpats** [comment]
у нас он монополист, ничего отвечать не будет. не хочешь не пользуйся. Буду побывать что-то с провайдером сделать. Порт из вне закрыт как я понимаю

**Comment by vvip-68** [comment]
А как утилита, что вы выше приводили синхронизируется? Ей то можно верить. И она, вроде как, тоже по 123 порту работает.

**Comment by igorpats** [comment]
Какая утилита? port cheker просто порты проверяет

**Comment by vvip-68** [comment]
NtpQuery. Где-то в самом верху ветки

**Comment by AlexxVel** [comment]
Позавчера тоже имел проблемы с получением времени по NTP. Версия платформы esp8266 2.6.3
Изначально сменил #define DEFAULT_NTP_SERVER "pool.ntp.org" // было "ru.pool.ntp.org"

WiFi.hostByName(ntpServerName, timeServerIP); - функция не отрабатывает и идет на "аварийный" IP. Я его сменил на тот, который у меня DNS-сился из коммандной строки (вроде начинался на 5.32.x.x - сейчас нет возможности посмотреть, т.к. не дома )  прямо в прошивке
#if defined(ESP8266)
  if (!timeServerIP.isSet()) timeServerIP.fromString(F("5.32.x.y"));  // тут было 192.36.143.130 
#endif
После этого все заработало...

**Comment by igorpats** [comment]
ntpquerty неизвестно как работает, но если сервер рабочий, оно данные получает

**Comment by igorpats** [comment]
Alex, вы сменили на тот адрес по которому отозвался pool.ntp.org?

**Comment by AlexxVel** [comment]
да

**Comment by AlexxVel** [comment]
в командной строке набрал ping pool.ntp.org
IP оттуда вписал в clock.ino в 84-ю строку. Перекомпилил и загрузил в wemos d1. И все заработало.

**Comment by igorpats** [comment]
я побывал играться с локальными серверами по вашей методике. 
![2019-12-25_14-28-36](https://user-images.githubusercontent.com/59146149/71444526-f3bf6700-2722-11ea-9c31-42e149dd3738.png)
не получалось, попробую еще, спасибо

**Comment by igorpats** [comment]
wip, а ты с библиотекой ntp не разбирался? странно что через оную работает

**Comment by igorpats** [comment]
Alex, у вас тоже только на 2.6.3 wemos адекватно цветопередачу дает?

**Comment by AlexxVel** [comment]
Как вариант - попробуйте еще откатить платформу до версии 2.5.2 (это в Менеджере плат). Возможно WiFi.hostByName(ntpServerName, timeServerIP) будет отрабатывать корректно...

**Comment by AlexxVel** [comment]
Насчет " только на 2.6.3 wemos адекватно цветопередачу дает".  Честно говоря - на данный момент у меня матрица на лоджии (19x10) работает на Arduino pro mini + RTC DS3231 (код от Сергея Козлова с оптимизацией памяти). Позавчера пробовал перейти на Wemos D1 mini, но пока отказался от него, т.к. бегущий текст скачет как фиг-знает кто... Ферритов всяких повесил штук 6 и на линии питания и на сигнальную линию. Электролит дополнительный 1000x16В (на меньшее напряжение не нашлось) на питание Wemos напаял, Диод на плюсовую линию к Wemos  тоже поставил. С компьютерного блока питания у меня идет 5.01V (замерял достаточно точным UT61). Еще уменьшить напряжение питания у меня нет возможности, разве что какой-то мощный диод еще поставить на питание матрицы... Но эксперименты продолжаю... (у меня достаточно длинная сигнальная линия - 4,5 метра от контроллера до первого RGB-диода)

**Comment by igorpats** [comment]
Alex, матрица 13х19, на wemose перестают вылазить проблемы в отображении исключительно при:
оригинальной fastled 3.3.2(не от гайвера)
esp8266 2.6.3
и таких настройках:
![2019-12-25_15-25-17](https://user-images.githubusercontent.com/59146149/71445437-e3ab8580-272a-11ea-905a-44e264ba4389.png)
Питание ровно 5, кондер по питанию 500, все
nodemcu и на других конфигурациях работает
При других конфигурациях были такие-же проблемы как и у тебя (текст крашиться, снежинки цвет меняют, в кубике при движении артефакты вылазили)

**Comment by AlexxVel** [comment]
FastLED 3.3.2 оригинальная; esp8266 2.6.3; настройки абсолютно такие-же (тоже выбрано именно NodeMCU 1.0), кроме Flash Size (FS я выбираю 1Mb, но это влиять не должно). Единственно у меня сам контроллер не NodeMCU, а Wemos D1 mini. Забыл добавить - управляющий сигнал у меня снимается с линии D3 через резистор 220 Ом.

**Comment by igorpats** [comment]
резистор стоит схожего номинала, я побывал на разных платах запускать, для wemosa только на такой конфигурации работает. Настройки это для wemosa скинуты, при использовании wemosa плату выбираем как на фото. Посмотри чтобы других библиотек fastled не было нигде, в папке программы и документах.

**Comment by AlexxVel** [comment]
У меня портабельный вариант Arduino - все в одной папке. Все библиотеки в D:\arduino-1.8.5\portable\sketchbook\libraries\  Если-бы где были другие библиотеки FastLed - ругалось-бы на дублирование библиотек. Кроме того при компиляции там варнингом выводится версия библиотеки (с путями): pragma message "FastLED version 3.003.002". Попробую еще диод по питанию wemos убрать. Еще жду с Ali другой БП (5V 5А) с подстройкой напряжения - правда не знаю когда придет. Также есть мысля пока запитать wemos от отдельного маломощного БП (может быть даже трансформаторного, а не импульсного) с объединением земель...

**Comment by igorpats** [comment]
У меня такой БП на 10 A. У меня напруга никак не влияет, а вот то что описал очень. и еще тру ее flash download tools

**Comment by igorpats** [comment]
Вот чего я добился, синхронизации с локальной машиной в сети
![2019-12-25_18-47-51](https://user-images.githubusercontent.com/59146149/71447997-40b53480-2747-11ea-9c06-bd1af2b82eaa.png)

**Comment by AlexxVel** [comment]
Посмотрел дома - я прописал аварийным IP 5.135.3.88
Лог у меня такой: 
...
WiFi подключен. IP адрес: 192.168.0.106

UDP-сервер на порту 2390
Включен эффект 'Водоворот'
NTP-сервер pool.ntp.org -> 5.135.3.88
Отправка NTP пакета на сервер pool.ntp.org
Таймаут NTP запроса!
NTP-сервер pool.ntp.org -> 5.135.3.88
Отправка NTP пакета на сервер pool.ntp.org
UDP пакeт размером 48 от 5.135.3.88, порт 123
Разбор пакета NTP
Секунд с 1970: 1577301904
19:25 25 декабря 2019 года <- это уже я сам добавил в отладку (разбирался с проблемой TimeZone )...

PS: кстати у меня дома платформа оказалась 2.6.2. Сейчас обновлю до 2.6.3, выпаяю диод и посмотрю насчет фантомным мерцаний...

**Comment by igorpats** [comment]
буду прикручивать ntp на малину или на роутер. На сколько точны данные часики? за какое время и на сколько убегает время?

**Comment by igorpats** [comment]
только на 2.6.3 wemos без артефактов заработал

**Comment by AlexxVel** [comment]
Решил проблему неработы WiFi.hostByName(ntpServerName, timeServerIP);
Проблема в том, что для контроллера не определен DNS сервер, поэтому hostbyname возращает 0.0.0.0
Чтобы работало - правим GyverMatrixOS_v1.15.ino в функции startWiFi:
    if (IP_STA[0] + IP_STA[1] + IP_STA[2] + IP_STA[3] > 0) {
      WiFi.config(IPAddress(IP_STA[0], IP_STA[1], IP_STA[2], IP_STA[3]),  // 192.168.0.106
                  IPAddress(IP_STA[0], IP_STA[1], IP_STA[2], 1),          // Gateway 192.168.0.1
                  IPAddress(255, 255, 255, 0),
                  IPAddress(IP_STA[0], IP_STA[1], IP_STA[2], 1),        // DNS1 192.168.0.1
                  IPAddress(8, 8, 8, 8));       // DNS2 8.8.8.8  
    WiFi.begin(ssid, pass);

**Comment by AlexxVel** [comment]
**vvip-68**, поправь, пожалуйста (см. предыдущее мое сообщение)

**Comment by igorpats** [comment]
ох я ж и валенок, спасибо что натолкнул своими коментами. 
IPAddress(IP_STA[0], IP_STA[1], IP_STA[2], 1), // Gateway 192.168.0.1
у меня же два роутера, а это адрес как раз второго который и поднимает это соединение и он у меня не такой

**Comment by vvip-68** [comment]
Хорошо, добавил. Но если dns не задается - 0.0.0.0 он же по умолчанию IP шлюза (192.168.0.1)  использует как DNS... И у всех вроде так и работает...

**Comment by AlexxVel** [comment]
Если DNS явно через WiFi.config не задано, то WiFi.dnsIP(0) получается (ip unk) (или как-то так - вчера видел у себя в отладке)
При этом при любом имени сервера WiFi.hostByName(любое_имя, timeServerIP)   timeServerIP будет равно 0.0.0.0 и пойдет на "аварийный" (заданный явно) IP 192.36.143.130 (поэтому "у всех вроде и работает").  А вот если задать явно DNS через WiFi.config, то hostByName отрабатывает корректно. По крайней мере на платформах 2.6.2 и 2.6.3 именно так  (добавлял отладочные сообщения и смотрел).   PS: Вот нашел и подтверждение, что до версии 2.4.1 включительно все работало без заданного явно DNS, а начиная с версии 2.4.2 перестало  https://github.com/esp8266/Arduino/issues/5328

**Comment by igorpats** [comment]
Alex, победил свой wemos?

**Comment by AlexxVel** [comment]
Пока нет, артефактов стало гораздо меньше (бегущая строка уже не пляшет), но не исчезли совсем - наблюдаются вспышки. Буду еще с питанием мудрить и, может быть, куплю еще экранированный провод (типа микрофонного) и поставлю вместо управляющего (экран одной точной на землю посажу)

**Comment by igorpats** [comment]
Проще nodemcu купить

**Comment by ant1xr1st87** [comment]
> Никак не могу настроить синхронизацию с ntp сервером. Проблема в следующем:
> 22:36:02.254 -> NTP-сервер [www.belgim.by](http://www.belgim.by) -> 178.124.164.107
> 22:36:02.254 -> Отправка NTP пакета на сервер [www.belgim.by](http://www.belgim.by)
> 22:36:07.075 -> UDP пакeт размером 6 от 192.168.1.218, порт 2390
> 22:36:07.075 -> Содержимое: $18 0;
> 22:36:07.244 -> Таймаут NTP запроса!
> И так постоянно какой-бы адрес не указывал. Не могу понять почему оно пакеты не принимает от сервера. Порт использовал 123 как в исходнике. Пробовал и другие.

У меня тоже проблема была такая. Начал копать с файервола. У меня стоит микротик 951й, я в нем попересоздавал кучу всяких правил, гугл говорит, что проблемы у многих с NTP в микротике, с чем связано не понятно(но мои подозрения, что провайдер блокирует некоторые IP адреса NTP серверов). Заколебался если честно. Через синхронизацию времени винды забиваю сервер ru.pool.ntp.org и вижу что синхронизация успешно. Лезу в микротик и смотрю на какой ИПшник был коннект на 123й порт. Сделал в микротике NTP-клиент+сервер, в клиенте указал полученный IP, ну а в прошивке и винде поставил NTP локальный адрес микротика. Все работает!

**Comment by ant1xr1st87** [comment]
> (у меня достаточно длинная сигнальная линия - 4,5 метра от контроллера до первого RGB-диода)

Мне кажется проблема артефактов в этом. Где-то тут читал, у АлексГайвера вроде, что проблемы из-за длины могут быть. Может быть попробовать сопротивление поменьше поставить на управляющую ногу?

**Comment by AlexxVel** [comment]
> Мне кажется проблема артефактов в этом

.Меньше длину (4.5м)не сделать, т.к. БП и контроллер - на подоконнике в комнате (в тепле), а гирлянда - на окне лоджии (как раз ближайшим концом к окну), а контроллер выносить "на мороз" (у нас до -35градусов бывает, лоджия не утепленная) считаю неразумным. Кроме того - артефактов при использовании Arduino Pro Mini вообще нет - только на Wemos D1 mini. Буду пробовать уменьшать питание на ленту... С сопротивлением тоже поэкспериментирую...

**Comment by igorpats** [comment]
4.5 метра это всего лишь длинна одной ленты. Отсоедините 50 диодов и посмотри на результат. А что с контроллером произойдет в -35? БП ещё возможно и опасно выносить, он греется немного. Так хоть на время укоротить кабель и посмотреть. У меня схожие условия с вами, гирлянда висит на лоджии холодной. Длинна управляющего метра 3 минимум. 3 соединения по пути на дюпонах. Wemos адекватно заработал только в том случае что описал. Nodemcu почему-то гораздо лояльнее относилась к всему выше сказанному.

**Comment by ant1xr1st87** [comment]
На морозе ни контроллеру ни БП ничего не станется. Мороз и жара критичны только для АКБ. 
А какова локализация артефактов? По всей ленте? Или может на последних отрезках гирлянды? Питание последовательное? Может стоит сделать параллельное?

**Comment by AlexxVel** [comment]
Питание параллельное к каждой вертикальной линии из 10 светодиодов. 4 основных точки приложения питания (от БП сечением 1,5мм2) и потом еще питание снизу раскинуто проводами 0.35. Артефакты были по всей ленте - заметны при бегущей строке или при часах, наложенных на полноэкранные эффекты шумов (noise). Сейчас полностью избавился от артефактов. Что сделал: по питанию на Wemos D1 mini был до этого подпаян электролит 1000x25V, заменил его на 3300x6.3V и еще подпаял керамический кондер 100нФ. Кроме того выходную сигнальную линию перенес с контакта D3, на контакт D5 (GPIO14) (он с другой стороны платы - теперь линия управления сразу отходит в сторону от Wemos (ранее пересекала его)).  Сейчас вот так вот выглядит:
![wemos](https://user-images.githubusercontent.com/59178758/71557615-8892cf00-2a59-11ea-9745-24b0d4a2e032.jpg)

**Comment by igorpats** [comment]
А конденсатор на 1000 новым был? Может у него характеристики уплыли или разные ставили. Я даже новые проверяю теперь.

**Comment by AlexxVel** [comment]
Да, 1000x25V был новым (ESR замерить нечем, тестером сейчас измерил емкость - 926мкФ), производитель Chongx.  А вот 3300x6.3V б/у, выпаян со старой материнки 2003 года (еще socket A)...

**Comment by AlexxVel** [comment]
Шайтан однако. Добавил в код функциональность по выводу строки - До нового года осталось столько-то часов, никакие характеристики платы, ни версию платформы не менял (автообновление отключено). Залил в свой Wemos D1 mini - и снова появились артефакты. Вообще ничего не понимаю...

**Comment by fsb054c** [comment]
У меня 3 матрицы - на балконе, у детей под потолком и лампа. Этот фликеринг был неприятным сюрпризом. Я перебрал платы, вольтаж питания, длины кабелей, емкостной обвес, резисторы, но занятно было то, что он не проявлялся на конкретных прошивках - все старые и на лампе.
В дельте, в районе 13 версии (если правильно помню), убрали следующие параметры
#define FASTLED_INTERRUPT_RETRY_COUNT 0
#define FASTLED_ALLOW_INTERRUPTS 0
Проблема ушла на 100%. Почему выпилили не знаю, возможно это приводит к другим проблемам, но таковые мной не замечены.

С нетерпением жду комита мода со строкой остатка времени до НГ ;-)

**Comment by igorpats** [comment]
Alex, скидывай обновление, проверим на других платах.

**Comment by AlexxVel** [comment]
в custom.ino добавляем
```
String WriteDays(int iDays){
  if ((iDays >= 5) && (iDays <= 20)) return " ДНЕЙ";
  else {
    iDays = iDays %10;
    if (iDays == 1) return " ДЕНЬ";
    else if ((iDays >= 2) && (iDays <=4)) return " ДНЯ";
    else return " ДНЕЙ";
  }
 
}

String WriteHours(int iHours){
  if ((iHours >= 5) && (iHours <= 20)) return " ЧАСОВ";
  else {
    iHours = iHours %10;
    if (iHours == 1) return " ЧАС";
    else if ((iHours >= 2) && (iHours <=4)) return " ЧАСА";
    else return " ЧАСОВ";
  }
}

String WriteMinutes(int iMinutes){
  if ((iMinutes >= 5) && (iMinutes <= 20)) return " МИНУТ";
  else {
    iMinutes = iMinutes %10;
    if (iMinutes == 1) return " МИНУТА";
    else if ((iMinutes >= 2) && (iMinutes <=4)) return " МИНУТЫ";
    else return " МИНУТ";
  }
}

String WriteSeconds(int iSeconds){
  if ((iSeconds >= 5) && (iSeconds <= 20)) return " СЕКУНД";
  else {
    iSeconds = iSeconds %10;
    if (iSeconds == 1) return " СЕКУНДА";
    else if ((iSeconds >= 2) && (iSeconds <=4)) return " СЕКУНДЫ";
    else return " СЕКУНД";
  }
}
String DO_NY = "ДО НОВОГО ГОДА ОСТАЛОСЬ - ";
String WriteCounter(unsigned long tsCurRemained){
  int iDays = tsCurRemained/(24*3600);
  int iHours = tsCurRemained/3600;
  int iMinutes = tsCurRemained/60;
  int iSeconds = tsCurRemained;
  
  if (iDays > 1) return DO_NY + String(iDays,DEC) + WriteDays(iDays);
  else {
    if (iHours >= 1) return DO_NY + String(iHours,DEC) + WriteHours(iHours);
    else {
      if (iMinutes >= 1)return DO_NY + String(iMinutes,DEC) + WriteMinutes(iMinutes);
      else {
        if (iSeconds > 1)return DO_NY + String(iSeconds,DEC) + WriteSeconds(iSeconds);
        else {
          return String("С НОВЫМ ГОДОМ!!!");
        }
      }
    }
  }
}
```
в void customModes(byte aMode) {  
```
    case DEMO_TEXT_2:     //fillString(TEXT_3, 2); break;  
      { 
        long DiffTime=1577836800-now();
        if (DiffTime<0) fillString(TEXT_3, 2);  
         else fillString(WriteCounter(DiffTime),1);
      }
      break;
```
Ну и в clock.ino в конец функции parseNTP() добавил для отладки (контроля правильности):
```
    long DiffTime=1577836800-now();
    Serial.println(DiffTime);
    if (DiffTime>0) Serial.println(WriteCounter(DiffTime));
```

**Comment by AlexxVel** [comment]
У меня на основе 15-й версии. Сделал поиск по коду - параметры FASTLED_INTERRUPT_RETRY_COUNT и FASTLED_ALLOW_INTERRUPTS дефайнами в коде не определены. Соответственно исходя из led_sysdefs_esp8266.h получаем 
```
#ifndef FASTLED_ALLOW_INTERRUPTS
# define FASTLED_ALLOW_INTERRUPTS 1
# define INTERRUPT_THRESHOLD 0
#endif
```
а исходя из кода fastled_config.h
```
#ifndef FASTLED_INTERRUPT_RETRY_COUNT
#define FASTLED_INTERRUPT_RETRY_COUNT 2
#endif
```

**Comment by fsb054c** [comment]
Алекс, спасибо за код.

По дефайнам все так. На 15 версии у меня нормально работает только с нулями.

Такие же параметры в GyverLamp_v1.5.5 (и ранее), которая не фликерит. Это и навело на мысль, что проблема решается из софта.

**Comment by AlexxVel** [comment]
Немного причесал код (вместо 4-х функций: WriteDays,WriteMinutes,WriteHours,WriteSeconds сделал одну WriteVremOtr, остальное как 3 поста назад):
```
static const String NamesVrem1[4] = { " ДНЕЙ", " ЧАСОВ", " МИНУТ", " СЕКУНД"};
static const String NamesVrem2[4] = { " ДЕНЬ", " ЧАС", " МИНУТА", " СЕКУНДА"};
static const String NamesVrem3[4] = { " ДНЯ", " ЧАСА", " МИНУТЫ", " СЕКУНДЫ"};

String WriteVremOtr(int iVrOtr, byte typeVrOtr){
  if ((iVrOtr >= 5) && (iVrOtr <= 20)) return NamesVrem1[typeVrOtr];
  else {
    iVrOtr = iVrOtr %10;
    if (iVrOtr == 1) return NamesVrem2[typeVrOtr];
    else if ((iVrOtr >= 2) && (iVrOtr <=4)) return NamesVrem3[typeVrOtr];
    else return NamesVrem1[typeVrOtr];
  }
}

String DO_NY = "ДО НОВОГО ГОДА ОСТАЛОСЬ - ";
String WriteCounter(unsigned long tsCurRemained){
  int iDays = tsCurRemained/(24*3600);
  int iHours = tsCurRemained/3600;
  int iMinutes = tsCurRemained/60;
  int iSeconds = tsCurRemained;
  
  if (iDays > 1) return DO_NY + String(iDays,DEC) + WriteVremOtr(iDays,0);
  else {
    if (iHours >= 1) return DO_NY + String(iHours,DEC) + WriteVremOtr(iHours,1);
    else {
      if (iMinutes >= 1)return DO_NY + String(iMinutes,DEC) + WriteVremOtr(iMinutes,2);
      else {
        if (iSeconds > 1)return DO_NY + String(iSeconds,DEC) + WriteVremOtr(iSeconds,3);
        else {
          return String("С НОВЫМ ГОДОМ!!!");
        }
      }
    }
  }
}

```

**Comment by fsb054c** [comment]
Алекс, а фликеринг пропал? Помогло?

**Comment by AlexxVel** [comment]
Пока за окном еще светло. Через полчаса буду пробовать...

**Comment by ACKET2009** [comment]
Ребят, может перезальёте скетчи поправленные? У нас уже время - пора бокалы наливать :) Но ещё успеваем

**Comment by fsb054c** [comment]
Я подправил вот так
```
String WriteCounter(unsigned long tsCurRemained){
  int iDays = tsCurRemained/(24*3600);
  int iHours = tsCurRemained/3600;
  int iMinutes = tsCurRemained/60;
  int iSeconds = tsCurRemained;
  
  if (iDays > 1) return DO_NY + String(iDays,DEC) + WriteVremOtr(iDays,0) + ", " + String(iHours,DEC) + WriteVremOtr(iHours,1) + ", " + String(iMinutes,DEC) + WriteVremOtr(iMinutes,2) + ", "  + String(iSeconds,DEC) + WriteVremOtr(iSeconds,3);
  else {
    if (iHours >= 1) return DO_NY + String(iHours,DEC) + WriteVremOtr(iHours,1) + ", " + String(iMinutes,DEC) + WriteVremOtr(iMinutes,2) + ", "  + String(iSeconds,DEC) + WriteVremOtr(iSeconds,3);
    else {
      if (iMinutes >= 1)return DO_NY + String(iMinutes,DEC) + WriteVremOtr(iMinutes,2) + ", "  + String(iSeconds,DEC) + WriteVremOtr(iSeconds,3);
      else {
        if (iSeconds > 1)return DO_NY  + String(iSeconds,DEC) + WriteVremOtr(iSeconds,3);
        else {
          return String("С НОВЫМ ГОДОМ!!!");
        }
      }
    }
  }
}
```

Получаются бегущие часы, минуты и секунды уменьшающиеся в процессе движения

Еще в setRandomMode2() сделал после byte newMode = random(0, MODES_AMOUNT - 1);" вставку
```
    byte counterToNY = random(0, 2);
    if (counterToNY==0) newMode=DEMO_TEXT_2;
```
что бы увеличить вероятность выпадения этого режима.

Как времянка для эвента до НГ подойдет :-)

**Comment by AlexxVel** [comment]
Сделал
#define FASTLED_INTERRUPT_RETRY_COUNT 0
#define FASTLED_ALLOW_INTERRUPTS 0
до подключения #include "FastLED.h"
Такое ощущение, что артефактов стало еще больше. Даже стены в игре Лабиринт теперь иногда моргают красным...

**Comment by fsb054c** [comment]
У меня так же переопределено до всех инклюдов.
Печаль, значит возможно этимология проблемы разная у нас.

**Comment by igorpats** [comment]
У меня при отсчете выводит просто дату текущую, что-то я не то делаю

**Comment by AlexxVel** [comment]
Опять избавился от артефактов. Не знаю, надолго-ли... Понизил питание на ленту с 5.01В
 до 4.3В за счет установки советского выпрямительного диода, рассчитанного на ток 5А)
![diod](https://user-images.githubusercontent.com/59178758/71628246-20ceb680-2c08-11ea-9074-2ed2f2e13eaf.jpg)

**Comment by ant1xr1st87** [comment]
> Опять избавился от артефактов. Не знаю, надолго-ли... Понизил питание на ленту с 5.01В
> до 4.3В за счет установки советского выпрямительного диода, рассчитанного на ток 5А)
> ![diod](https://user-images.githubusercontent.com/59178758/71628246-20ceb680-2c08-11ea-9074-2ed2f2e13eaf.jpg)

Почему то сразу вспомнил пост с Пикабу про [заземление](https://pikabu.ru/story/zazemleno_6548811)😁😁😁
