### ISSUE TITLE
Режимы по времени

### ISSUE THREAD

**Issue by ACKET2009** [vvip-68/GyverMatrixWiFi#26]
Здравствуйте! Сделал себе на окно вместо новогодней шторы - слов нет, потрясающе работает!! Есть 2 момента - если не отключать игру в лабиринт, регулярно подвисает на ней а то и перезапускается. В остальном никаких ошибок не обнаружил. А по второму - есть всего 2 режима по времени, то есть можно поставить время включения и время выключения. С точки зрения применения такой штуки на окне было бы логично добавить ещё 2 режима. Днём огоньков почти не видно и смысла зажигать гирлянду нет, поэтому хотелось бы, чтобы включалась вечером, когда темнеет и выключалась, когда поздно совсем, затем снова включалась в утренние часы пока темно и выключалась с рассветом... Если это не сложно, конечно, в приложении как раз пол страницы с режимами по времени пустые, а добавить 2 пункта и будет красота! :) А, вот ещё забыл - для деморежима есть 3 надписи бегущих строки, их как-то можно вынести в приложение на телефоне, чтобы можно было менять без перепрошивки?

**Comment by vvip-68** [comment]
Все это можно. Но нужно переделывать и прошивку и программу.
По трем строкам, задаваемым в приложении - вот-вот уже собирался, но так руки и не дошли.
По еще двум режимам - теоретически можно, практически - приложение в конструкторе и так уже еле шевелится. Очень некомфортно там что-то переделывать.
Резюме - может быть когда-нибудь. Не последний же Новый год...

**Comment by ACKET2009** [comment]
Да, пробовал я в конструкторе на сайте просто посмотреть как и что делается - нереально тормозит... я думал это мой компьютер предпенсионного возраста... Да, там всё туго...
