### ISSUE TITLE
Включение по расписанию

### ISSUE THREAD

**Issue by ghost** [vvip-68/GyverMatrixWiFi#27]
Приветствую. Настроил включение-выключение по времени. Но, включена матрица была в демо режиме с автосменой эффектов, потом выключается, а включается в следующий раз всегда в ручном режиме. Причем не важно какая цифра стоит в поле "авторежим через" сам авторежим не включается. Только вручную каждый раз.

**Comment by vvip-68** [comment]
Ничё не понял.  У меня полгода уже - в 23 выключить (или в ночные часы), в 8 утра - случайный режим - то есть демо/автосмена. Всё работает. Если вы указываете при включении конкретный режим - ну так он и включится и будет в нем как в "ручном" режиме работать. Что не так то?

**Comment by ghost** [comment]
Ну да, конкретный стоит. Думал что если стоит цифра в "авторежим через" то через н-ное число должен включиться авторежим со сменой. Попробовал "случайный эффект", да, действительно, так работает
