### ISSUE TITLE
Включение/выключение по расписанию

### ISSUE THREAD

**Issue by serg-74** [vvip-68/GyverMatrixWiFi#3]
Здравствуйте.
Есть ли возможность возможность сделать включение/выключение (опционально) матрицы по расписанию (например, включение в 17.30, выключение в 23.00). Т.е. ESP8266 включена постоянно, а на матрицу сигнал подается согласно расписания. Как вариант, возможно использовать компьютерный блок питания ATX - ESP8266 питать от 5В дежурного режима блока питания, а для питания ленты использовать линию 5В, управлять блоком питания можно сигналом с ESP8266.

**Comment by vvip-68** [comment]
Теоретически это сделать не сложно. А практически - ну, может, руки и дойдут когда-нибудь... Это рутинная не интересная доработка программы. К тому же нужно менять управление в Android-программе (время, когда выключить, когда включить, чекбоксы использовать / нет) - это всё в Thunkable, а он и с текущим функционалом уже еле шевелится. Что-то менять там - одно мучение...

**Comment by vvip-68** [comment]
Сделал такие режимы. В приложении на смартфоне добавлен пункт в списке выбора / страничка настроек "Режимы по времени". Два режима для которых можно задать время срабатывания и действие, которое нужно выполнить. Если выбрано "Нет действия" - при наступлении указанного времени ничего не происходит, иначе выполняется одно из действий, указанных в списке.
Список действий:
  - Выключить матрицу
  - Включить ночные часы
  - Включить камин с часами
  - Включить бегущую строку (текст нужно задать в настройках текста бегущей строки)
  - Включить случайный эффект и далее смена эффектов - режим демонстрации
  - Включить выбранный из списка эффект . Автосмена на другой эффект отключена.

То есть, для 23:00 вы можете выбрать действие "Выключить матрицу", а для 17:30 например - "Случайный эффект". ESP8266 при этом остается активной - матрицей можно управлять со смартфона или кнопкой, если включен будильник - он сработает. По завершении работы будильника матрица останется включенной в режиме отображения часов.

**Comment by vvip-68** [comment]
Исправление к выше (в связи с выходом новой версии):
"... По завершении работы будильника матрица вернется в режим, который был до срабатывания будильника. То есть, если матрица была "выключена" - после завершения работы будильника она вернется в состояние "выключено". "
