### ISSUE TITLE
Не работает синхронизация времени

### ISSUE THREAD

**Issue by LaMarmota** [vvip-68/GyverMatrixWiFi#30]
NTP-сервер ru.pool.ntp.org -> 192.36.143.130
Отправка NTP пакета на сервер ru.pool.ntp.org
Таймаут NTP запроса!

И так постоянно... Пробовал разные платы (NodeMCU, Wemos). WiFi подключается и работает нормально.
В чем может быть проблема?

**Comment by vvip-68** [comment]
Судя по приведенному выше сообщению - у вас устаревшая версия прошивки.
Синхронизация может также не работать по причине того, что ваш провайдер закрыл порт по которому получаются NTP пакеты (123); может быть в настройках роутера что-то заблокировано.

**Comment by LaMarmota** [comment]
Прошивку скачивал последнюю отсюда. Библиотеки все скопировал. Порты точно не закрыты. Есть еще варианты в чем может быть дело?

**Comment by vvip-68** [comment]
Других вариантов нет.
1. Тут кто-то уже писал про эту проблему. Именно после обсуждения было предложено изменить процедуру подключения к сети - использовать вариант инициализации с указанием IP DNS серверов. После изменения проблема решилась.
2. Судя по тому какой вывод вы привели выше - У ВАС СТАРАЯ ВЕРСИЯ, в которых этих изменений нет.
3. Тут кто-то уже писал (по поводу другой проблемы, правда) - "я скачал отсюда последнюю версию - там нет того-то и того-то". Пока носом не ткнул в текст скетча прям тут на GITe в файл, что все изменения есть и сделаны еще месяц назад, утверждал что у него последняя версия скачана. Потом все же как-то скачал действительно последнюю версию и его проблема исчезла. Проверьте еще раз - действительно ли у вас последняя версия, со всеми исправлениями.
