### ISSUE TITLE
управление через MQTT?

### ISSUE THREAD

**Issue by alekseyn1** [vvip-68/GyverMatrixWiFi#31]
Здравствуйте,
Возможно ли соединить Ваш проект по упраляемой по MQTT матрице с этим проектом? 
Цель: передавать бегущую строку и переключать режимы через Home Assistant (работающий на MQTT)
Заранее благодарю за ответ.
Алексей

**Comment by vvip-68** [comment]
Вполне возможно. Код открыт. Делайте форк проекта и добавляйте управление через MQTT.
