### ISSUE TITLE
Матрица

### ISSUE THREAD

**Issue by Craimerix** [vvip-68/GyverMatrixWiFi#37]
Привет. Очень понравилась твоя прошивка и приложение, но такое вопрос: собрал я к примеру рюкзак по видео Гайвера, перепаивать схему не очень хочется. Можно ли загрузить просто твою прошивку? Будет ли оно работать без дополнительных элементов?

**Comment by vvip-68** [comment]
Можно. Будет. Если не перепаивать - возможно в прошивке потребуется скорректировать пин на ленту. Сейчас D2 - я не помню куда подключен в рюкзаке. 
А не проще было просто взять и попробовать?
