### ISSUE TITLE
Матрица 27х6 nodemcu не отображаются часы на фоне эффектов что я делаю не так?

### ISSUE THREAD

**Issue by tribunskiysm** [vvip-68/GyverMatrixWiFi#39]
У меня матрица 27х6 nodemcu не отображаются часы поверх эффекта что я делаю не так?
Что может быть нетак. В программе невозможно выбрать эффект Часы, при его выборе автоматически включается другой эффект - звездопад.
В программе WiFi Matrix в разделе Текст - сообщение что Размеры матрицы недостаточны но текст отображается немного подрезанным снизу - можно ли както уменьшить шрифт разблокировать этот раздел в программе?
Хотелось использовать матрицу как часы с бегущей строкой, очень хорошо работают игры runner и змейка)

**Comment by vvip-68** [comment]
Чаcы: для часов в этом проекте требуется минимум 7 строк текста. Почему - не помню. Попробуйте в основном файле в строке 257 проверку исправить с 7 до 5. Может быть часы заработают, может быть будут отображаться "криво".

Текст: ну ясно же написано - размер матрицы недостаточный. Делайте хотя бы 8 строк. Это минимум для бегущей строки.
Для уменьшения шрифта - берете листок в клеточку и пытаетесь нарисовать буквы высотой в 6 точек. Нли получится - идете в файл fonts.h и переписываете там образы букв с высоты 8 на ваши высотой 6. Далее в runningText.ino переписываете процедуру drawLetter и все что она вызывает так, чтобы они работали с буквами не 8 точек, а нарисованными вами 6-точечными.

**Comment by tribunskiysm** [comment]
Спасибо буду пробовать. С часами разобрался в строке 256 и 257 поправил HEIGHT на 6. Часы появились.
