### ISSUE TITLE
Как победить глюки?

### ISSUE THREAD

**Issue by teuchezh** [vvip-68/GyverMatrixWiFi#4]
Под глюками подразумевается включение группы случайных светодиодов.
Пробовал понижать напряжение на ноде до 4.5 и ниже на NodeMCU через Buck преобразователь, но это ничего не дало, так же кинул на выход преобразователя параллельно конденсатор 6.3v  1000uF для сглаживания на случай помех от пульсаций, что так же не дало результата.
(Тестирую на маленькой самосборной матрице 6х6 из ленты, в дальнейшем контроллер будет подключен на большом окне 2.4×1.4м)

**Comment by serg-74** [comment]
Напряжение надо понижать не на контроллере, а на ленте (матрице).

**Comment by teuchezh** [comment]
![image](https://user-images.githubusercontent.com/40827089/57129620-a9f2cc80-6d9f-11e9-886e-823053123e25.png)

Хорошо, попробую

**Comment by teuchezh** [comment]
Чекнул, все то же самое

**Comment by vvip-68** [comment]
Напряжение нужно понижать на всем сразу - и на контроллере и на матрице. Уровни должны быть согласованы. Про то, почему могут быть такие глюки - у Гувера расписано https://alexgyver.ru/gyvermatrixbt/. Других вариантов нет.
Могу предложить для теста питание с БП подавать только на ленту, землю МК и ленты - связать, сам МК питать от USB подключенному к компу.
