### ISSUE TITLE
Проблема с приложением PanelWifi

### ISSUE THREAD

**Issue by Mija-ops** [vvip-68/GyverMatrixWiFi#40]
Не происходит подключение по wifi со смартфона.
Опишу свои действия по шагам.
1) Подключился к точке доступа, который раздал esp8266
2) В настройках прописал имя сети, пароль и присвоил ip, устройство отключило точку доступа, в роутере появилось новое устройство с заданным ранее ip ( подсеть правильная, остальные устройство такие же 
![image](https://user-images.githubusercontent.com/63531875/105833332-9d92b680-5ffb-11eb-9dc9-ada08dad877b.png)
![image](https://user-images.githubusercontent.com/63531875/105833492-d6329000-5ffb-11eb-9bb6-8d41c8c18797.png)
3)С компьютера все пингуется
![image](https://user-images.githubusercontent.com/63531875/105833902-6bce1f80-5ffc-11eb-82cf-1bc0b0b937aa.png)

4) Пробую уже по этому ip подключиться в приложении WiFiPanel. Не подключается
![image](https://user-images.githubusercontent.com/63531875/105833583-fbbf9980-5ffb-11eb-964e-46f9fa5e56fb.png)

В роутере отключения изоляция клиентов
![image](https://user-images.githubusercontent.com/63531875/105834105-a5068f80-5ffc-11eb-992b-916b726f569d.png)

Телефон: Xiaomi Mi Mix 2s
Роутер  Xiaomi Mi WiFi Router 4A GIGABIT с кастомной прошивкой Padavan

**Comment by vvip-68** [comment]
Добейтесь, чтобы пинговалось не только с компьютера, но и с телефона на котором установлено приложение. Как только с телефона (из приложения) пакеты начнут доходить до контроллера - соединение установится.

И из вашего скриншота с телефона вообще не видно подключен ли он к сети kv219.
Зато видно, что отправка идет на IP телефона, когда он подключен к точке доступа (в логах) - 192.168.4.2

**Comment by Mija-ops** [comment]
> Добейтесь, чтобы пинговалось не только с компьютера, но и с телефона на котором установлено приложение. Как только с телефона (из приложения) пакеты начнут доходить до контроллера - соединение установится.
> 
> И из вашего скриншота с телефона вообще не видно подключен ли он к сети kv219.
> Зато видно, что отправка идет на IP телефона, когда он подключен к точке доступа (в логах) - 192.168.4.2


А как этого добиться, если, уверен что и телефон и устройство находятся в одной подсети(На скриншоте роутер видно, что и телефон и устройство находятся в одной сети) ? Тогда вероятнее всего проблема в настройках роутер?

**Comment by vvip-68** [comment]
Я не знаю. С этим вопросов вам, вероятно, лучше обратиться в профильные форумы по сетевым настройкам и роутерам вообще и по данной модели роутера в частности.

**Comment by Mija-ops** [comment]
> Добейтесь, чтобы пинговалось не только с компьютера, но и с телефона на котором установлено приложение. Как только с телефона (из приложения) пакеты начнут доходить до контроллера - соединение установится.


Я удостоверился в том, что с телефона все пингуется в сторону устройства и пакеты доходят
![image](https://user-images.githubusercontent.com/63531875/105838058-29a7dc80-6002-11eb-92c1-39b30f3ca7dc.png)

**Comment by Mija-ops** [comment]
@vvip-68 
И что интересно, у устройства не открыт порт 2390( который по умолчанию
![image](https://user-images.githubusercontent.com/63531875/105839407-02eaa580-6004-11eb-824d-bdbf3d023f31.png)

**Comment by vvip-68** [comment]
Ну, попробуйте перепрошить контроллер с включенной опцией "Erase all" и заново все настроить.
Порт задается константой в скетче и насколько я помню это значение нигде не меняется.
У меня нет ответа почему в вашем случае порт не открыт.
Обновите версию ядра до актуальной, если это не так.
Вообще, странно обсуждать проект WiFiPanel в issues проекта WiFiMatrix...

**Comment by vvip-68** [comment]
А вы уверены, что телнетом можно подключиться?
У меня тоже телнет выдает ошибку подключения, однако приложение - соединяется.
Так что - это не показатель.
