### ISSUE TITLE
Annoying Pixel Dot

### ISSUE THREAD

**Issue by TimoUrban** [vvip-68/GyverMatrixWiFi#41]
Hi!
I tried to get this project running with a 16x16 pixel matrix powered by NodeMCU.

I compiled the software with lots of different variations of the ESP Board-Libary and the FastLED Libary but in any way I get an annoying first pixel dot in the bottom left corner. 
It depends on the libaries I used if its green, blue, pink, flashing or static. 

Picture: https://ibb.co/0hMYh2X

(I know, this project is outdated but I really wanted to get rid of this pixel, beacause I still running into trouble with the Android app when I am using the GyverPanel Code)

**Comment by vvip-68** [comment]
Hi,
do not use ESP8266 core version V3.x.x → it lead to issue you described.
Set ESP8266 core version 2.7.4 and rebuild project. It will solve the issue.
  
>Среда, 15 сентября 2021, 1:32 +07:00 от Timo ***@***.***>:
> 
> 
>Hi!
>I tried to get this project running with a 16x16 pixel matrix powered by NodeMCU.
>I compiled the software with lots of different variations of the ESP Board-Libary and the FastLED Libary but in any way I get an annoying first pixel dot in the bottom left corner.
>It depends on the libaries I used if its green, blue, pink, flashing or static.
>(I know, this project is outdated but I really wanted to get rid of this pixel, beacause I still running into trouble with the Android app when I am using the GyverPanel Code)
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
С уважением,
Вадим Пузанов

**Comment by TimoUrban** [comment]
Thank you for your fast reply!

I tried using the ESP8266 core version 2.7.4. and the matrix will not start. 
Tested it just now again and it won´t work.

Issue: https://ibb.co/MV6tVzq
Board config: https://ibb.co/tYQbG73

At the moment using FastLED verion 3.3.3. (I played around a lot with different versions)

//Edit: It is possible connect to the wifi access point but my inputs in the android app have no effects.

**Comment by TimoUrban** [comment]
I found out that every ESP 8266 core version below 3.0.0. is causing the same issue - the matrix is showing nothing except the dot I don´t want to have hahaha

**Comment by TimoUrban** [comment]
The next surprising fact: Depending on the number of demo page sometime the dot is gone: 

https://www.youtube.com/watch?v=_8l6tKloZJo

**Comment by vvip-68** [comment]
When you have definition 
#define LED_PIN  2     → core v3.x.x direct matrix signal to pin D4
When you have sme definition and core 2.7.4 signal directed to pin D2
 
Check that you have core v2.7.4 and signal pin connected to matrix is D2 (not D4)!
 

  
>Среда, 15 сентября 2021, 2:10 +07:00 от Timo ***@***.***>:
> 
> 
>I found out that every ESP 8266 core version below 3.0.0. is causing the same issue - the matrix is showing nothing expect the dot I don´t want to have hahaha
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
С уважением,
Вадим Пузанов

**Comment by vvip-68** [comment]
Othervise you may use definition as
#define LED_PIN  **D**2 -> this direct output signal on 2.7.4 into pin D4

Which issue do you have with android application in GyverPanel project?

**Comment by vvip-68** [comment]
Note, you MUST select mcu as 'NodeMCU v1.0' in IDE settings even you use really Wemos board instead of real NodeMCU

**Comment by TimoUrban** [comment]
> Othervise you may use definition as
> #define LED_PIN **D**2 -> this direct output signal on 2.7.4 into pin D4


Holy cow, I feel so dumb now! My data pin was connected to PIN D4 on the NodeMCU. Switched to PIN D2 and uploaded the script with esp8266 core version 2.7.4 solved my problem.
I swear, I read your instructions over ten times, trying to find the error. 
Buddy you saved my evening, thank you very much!

**Comment by TimoUrban** [comment]
> Which issue do you have with android application in GyverPanel project?
When I install the script on the NodeMCU and connect the Android App to the panel, my inputs are going crazy. When I try to select an effect the list of effects is scrolling really fast. 
Image uploads and drawing by hand is absolutely not working.

**Comment by vvip-68** [comment]
Thank you for support my project.
I recived your ‘thanks’ over PayPal :)
 

  
>Среда, 15 сентября 2021, 2:41 +07:00 от Timo ***@***.***>:
> 
> 
>Othervise you may use definition as
>#define LED_PIN  D 2 -> this direct output signal on 2.7.4 into pin D4
>Which issue do you have with android application in GyverPanel project?
Holy cow, I feel so dumb now! My data pin was connected to PIN D4 on the NodeMCU. Switched to PIN D2 and uploaded the script with esp8266 core version 2.7.4 solved my problem.
I swear, I read your instructions over ten times, trying to find the error.
Buddy you saved my evening :-)
—
You are receiving this because you commented.
Reply to this email directly,  view it on GitHub , or  unsubscribe .
Triage notifications on the go with GitHub Mobile for  iOS or  Android . 
 
 
С уважением,
Вадим Пузанов

**Comment by vvip-68** [comment]
> > Which issue do you have with android application in GyverPanel project?
> > When I install the script on the NodeMCU and connect the Android App to the panel, my inputs are going crazy. When I try to select an effect the list of effects is scrolling really fast.
> > Image uploads and drawing by hand is absolutely not working.

Could you somehow send me video with app behaviour?
I do not understand what do you mean 'going crasy' and scrolling the list of effects.

Do you use special application GyverPlayer for draw and upload images in GyverPanel project?
Do you use special android application from GyverPanel project (not the app from GyverMatrix project)?

**Comment by TimoUrban** [comment]
I promise I will send a video of the issue. But at the moment I am very happy running my matrix with the GyverMatrixWiFi Code :-)  First I want to finish my 3D printed case for the pixel matrix. 

The specs of the GyverPanelWiFi are also very interesting for me. I ordered another NodeMCU  board so I can install GyverPanelWifi again.

Do you want to send me an e-mail adress or what is the best place to discuss?

Best wishes
Timo

**Comment by vvip-68** [comment]
The best practice to quick communication is usage of VK dialog (messenger) here https://vk.com/iivanovii
but I guess you do not have an account in this social network.

You may try to use skype dialog to vvip68 or viber messenger or telegram messenger
Both of them require phone number to start communication, which I do not want to present public.
The same with email. So - either here or in skype or let me way to tell you phone number or email in private manner.

**Comment by TimoUrban** [comment]
I added you via Skype :-)
