### ISSUE TITLE
Прошу подсказать

### ISSUE THREAD

**Issue by lBoneSl** [vvip-68/GyverMatrixWiFi#42]
Плата прошилась (NodeMcu Lua v3)

В конце есть сообщение:

Leaving...
Hard resetting via RTS pin...

Но похоже перезагрузка не происходит и скетч не выполняется (или плату нужно самому перезагрузить?)
В мониторинге порта только это:

21:04:52.697 -> ⸮⸮⸮l⸮⸮⸮⸮⸮⸮⸮⸮

Соответственно нужен совет, что не так инструкции уже 10 раз пересмотрел

**Comment by vvip-68** [comment]
Вот эти надписи и означают, что загрузка успешно завершилась и плата перегрузилась

**Comment by lBoneSl** [comment]
> 
> 
> Вот эти надписи и означают, что загрузка успешно завершилась и плата перегрузилась

Спасибо, понял, тогда получает я не могу подключится через приложение GyverMatrix, адрес и порт использую что в скетче прописанны: 
#define udp_port 2390 
byte IP_STA[] = {192, 168, 0, 106}; 

Кстати, в инструкции написанно и есть скрин, что в менеджере порта будет отбражаться инфа, но у меня только выше описанные символы в одной строке

**Comment by vvip-68** [comment]
Скорость порта выставьте соответствующую указанной в прошивке - 115200 в правом нижнем углу монитора порта

**Comment by lBoneSl** [comment]
> 
> 
> Скорость порта выставьте соответствующую указанной в прошивке - 115200 в правом нижнем углу монитора порта

Спасибо, инфа теперь есть, только вопрос остался, что app к плате не подключается.
Я прошил сейчас похожую плату только ESP 32, скетч на ней тоже работает но коннекта через wifi c app нет

**Comment by vvip-68** [comment]
Может быть десятки причин и сказать почему именно у вас не коннектится - проблематично.
Что-нибудь в момент попытки коннекта в мониторе порта отображается?
- Может слабый сигнал с роутера
- Может телефон не подключен к той же сети, что устройство
- Может роутер не пропускает пакет и перенаправляет их по другому маршруту
- Может вы используете приложение от другой прошивки, из другого проекта
- ... Да всё что угодно.

Начните с того, что добейтесь, чтобы с вашего телефона матрица пинговалась. 
Найдите и установите соответствующую утилиту проверки связи и добейтесь чтоб телефон "видел" матрицу

**Comment by vvip-68** [comment]
> адрес и порт использую что в скетче прописанны:
#define udp_port 2390
byte IP_STA[] = {192, 168, 0, 106};

А в логе в мониторе порта пишется, что подключение к сети выполнено и именно этот адрес получила матрица?
Может она все же точку доступа создает 192.168.4.1? При 4х-кратном нажатии на кнопку IP адрес выводится бегущей строкой на матрицу?

**Comment by lBoneSl** [comment]
> 
> 
> > адрес и порт использую что в скетче прописанны:
> > #define udp_port 2390
> > byte IP_STA[] = {192, 168, 0, 106};
> 
> А в логе в мониторе порта пишется, что подключение к сети выполнено и именно этот адрес получила матрица? Может она все же точку доступа создает 192.168.4.1? При 4х-кратном нажатии на кнопку IP адрес выводится бегущей строкой на матрицу?

Спасибо, вроде разобрался, такой вопрос у меня матрица мобильная, а непосредственно напрямую телефон к матрице можно подключить? Или только открытый вайфай должен быть?

**Comment by lBoneSl** [comment]
Спасибо, все теперь точно разобрался, как вам можно благодарность выслать?

**Comment by vvip-68** [comment]
На гитхабе где брали проект (здесь вверху) - есть кнопка "Sponsor". Можно так поддержать проект.
Спасибо.
