### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by kost111233** [vvip-68/GyverMatrixWiFi#43]
Добрый вечер, долго собирался прежде чем написать. Изначально все режимы зависали на 30 секунды, пробовал все, питания понижал и тд, помогло только перепрошивка платы до заводских. Сейчас все работает, но до того момента,пока не подключу матрицу к домашнему вайфаю. У меня ип 192.168.31.1 у роутра, я в скетч ввожу например 192.168.31.100, прошивается, режимы работают, но больше нет точки доступа самой платы, не возможно подключится. Пробовал и в скетче вводить и в приложение, так же менял каждый раз eeprom.

**Comment by vvip-68** [comment]
Если после включения точка доступа не создается - значит устройство успешно подключилась к сети.
Принудительно создавать точку доступа даже когда она успешно подключилась к локальной сети - только если в настройках соединения в приложении установлена галка "Создавать точку доступа".
Принудительно остановить подключение к сети и создать точку доступа можно если при включении устройства в первые несколько секунд нажать н а кнопку.

Подключите устройство USB кабелем, откройте монитор порта и убедитесь, что устройство подключаясь к локальной сети получает именно тот адрес, который вы ожидаете (который вы указали в приложении при настройке подключения). Если адрес не попадает в диапазон подсетки роутера - принудительно включите точку доступа нажатием кнопки при старте устройства до того как оно успело подключиться к локальной сети.

Затем, из приложения подключитесь к точке доступа и настройте еще раз подключение к сети (имя сети, пароль, IP адрес, который должно получать устройство в сети).

По поводу "зависали на 30 секунды" - ничего сказать не могу. С таким не  сталкивался.

**Comment by vvip-68** [comment]
И - проект Gyver**Matrix**WiFi - устаревший, уже не поддерживается и ошибки не правятся, даже если они есть. Рекомендуется перейти на проект GyverPanelWiFi - там все те же возможности что и в этом проекте, плюс куча дополнительных возможностей.

**Comment by kost111233** [comment]
Я сначала и начал с вашего проекта, но не знал что проблема в плате, ужасно все тормозило. Ваш проект у меня работал с задержкой в минуту наверно, стоп кадр, поэтому решил этот попробовать, там задержки были меньше, сейчас все хорошо. 

Значит плата не может одновременно быть подключена к домашней сети и создавать свою точку доступа? Не знал об этом. Правильно понял, подключаю в сеть и чтоб зайти в приложение, нужно в первые секунды нажать на кнопку переключения режимов, тогда появится точка доступа самой платы и там уже все настраивать? 

Спасибо за помощь, буду пытаться запускать ваш проект. Единственное не понял по работе часов в описании, у меня маленькая матрица 20х10, видел видео других пользователей, они будут только как бегущая строка?

**Comment by vvip-68** [comment]
Они будут шрифтом 3x5, для которых достаточно ширины в 15 колонок. Для часов шрифтом 5x7 нужна ширина в 23 колонки минимум. Часы в бегущей строке будут шрифтом 5x8.

**Comment by vvip-68** [comment]
> Значит плата не может одновременно быть подключена к домашней сети и создавать свою точку доступа? Не знал об этом.

Плата МОЖЕТ быть одновременно в локальной сети и создавать точку доступа. Но для этого в настройках нужно поставить соответствующую галочку.

**Comment by kost111233** [comment]
Извините за глупые вопросы. Очень крутой проект, потрачено много сил и времени на него, даже инструкция есть. Но все равно появляются такие как я:)  спасибо за помощь

**Comment by vvip-68** [comment]
> Правильно понял, подключаю в сеть и чтоб зайти в приложение, нужно в первые секунды нажать на кнопку переключения режимов, тогда появится точка доступа самой платы и там уже все настраивать?

Плата подключается к локальной сети. Если подключение успешно - точка доступа не создается. Подключиться к плате можно из приложения через локальную сеть.

Если подключиться к сети не удалось - автоматически создается точка доступа. Подключиться из приложения можно и через точку доступа напрямую.

Если в настройках установить соответствующую галочку - плата будет И подключаться к локальной сети И создавать точку доступа. Подключиться можно и через сеть и через точку доступа.

**Comment by vvip-68** [comment]
Нажатие на кнопку в первые секунды отменяет подключение к локальной сети и создает точку доступа
