### ISSUE TITLE
Не видит ленту.

### ISSUE THREAD

**Issue by Paqwa12** [vvip-68/GyverMatrixWiFi#44]
Добрый вечер, недавно собрал данную сборку на NodeMcu и столкнулся с такой проблемой, плата не выводит изображение на ленту, все провода подключены в том числе и питание и на ленту и на плату, к приложению плата подключается.
Что делать?

**Comment by vvip-68** [comment]
Подключить ленту именно к тому пину микроконтроллера, на который выводится управляющий сигнал, а не к случайному. Плюс проверить, что лента подключена к пину контроллера входом (DIn), а не выходом (DOut).
