### ISSUE TITLE
file aia i cant use it with any app inventor or thunkable 

### ISSUE THREAD

**Issue by dio1985** [vvip-68/GyverMatrixWiFi#45]
file aia i cant use it with any app inventor or thunkable for last version 
can you help me??

**Comment by vvip-68** [comment]
I recommend you use next generation of application - [GyverPanelWiFi](https://github.com/vvip-68/GyverPanelWiFi)

**Comment by dio1985** [comment]
thank you. but when ver 1.12  GyverPanelWiFi.aia is opening with appInventor , 
But I get an error while opening the file (Error from Companion: Font asset not found /storage/emulated/0/AppInventor/assets/FontAwesome5Free-Solid-900.otf

**Comment by vvip-68** [comment]
Nothing to say... Never meet this issue. File is in Media folder of AppInventor and also is in local file system in project folder Android.
![image](https://user-images.githubusercontent.com/39353139/156110654-2e2c8a12-6746-4ef0-baef-60f824d27958.png)

![image](https://user-images.githubusercontent.com/39353139/156110703-cfdf2242-7258-496a-bdd0-f7e7c5893b1d.png)

**Comment by dio1985** [comment]
thank you. yes your any apk files and  xxxx.apk file after build from your any xxx.aia files is works well.

 but app inventor Menu  "connect > AI companion " 

i tried to conect to my phone  ,My phone and Inventor are connected to each other, but the text is not visible. The above mentioned error occurs. My phone version is Android 11.

**Comment by vvip-68** [comment]
It is question not for me. Try to ask AppInventor support team.

**Comment by dio1985** [comment]
thank you sir. solved the problems. your code and appInventor aia is perfact. but extension (YourFont)is not work for me as like android over 10.so changed extension. it works well. thank you
