### ISSUE TITLE
dawnColorSat2 causes a section type conflict with __c

### ISSUE THREAD

**Issue by yusufsulaiman** [vvip-68/GyverMatrixWiFi#5]
hi. i have error dawnColorSat2 causes a section type conflict with __c

**Comment by vvip-68** [comment]
Hi,
I have no such error. Possible you are doing something wrong.

**Comment by vvip-68** [comment]
Couldn`t reproduce issue.

**Comment by AndrewVlz** [comment]
Добрый день!

Получил такую же ошибку при компиляции Вашей программы.

"dawnColorSat2 causes a section type conflict with __c"

скетч effects.ino.

При этом dawnColorSat с таким же содержимым ошибок не вызывает.

Настройки компиляции, версия Arduino IDE прилагаются.

В чем может быть проблема?

Спасибо!
![Github1](https://user-images.githubusercontent.com/55710934/65448905-8873a980-de42-11e9-8729-e5d348c07ec1.png)
![Github2](https://user-images.githubusercontent.com/55710934/65448912-8dd0f400-de42-11e9-96cf-9f365826a892.png)

**Comment by vvip-68** [comment]
Снова скажу - ни разу не видел такой ошибки. Возможно это проблемы компилятора. У вас довольно старая версия IDE 1.8.2, попробуйте обновиться до последней - 1.8.10. На версиях IDE 1.8.9 и 1.8.10 такой ошибки при компиляции у меня не возникает.

**Comment by vvip-68** [comment]
Проблема в том, что у вас старая версия библиотеки ядра ESP8266 (скорее всего 2.4.x вместо рекомендованной 2.5.2) и вы совсем не читаете инструкции к проекту

**Comment by yusufsulaiman** [comment]
thanks for advice. i have made it 
https://www.youtube.com/watch?v=ZucOUIFpxck
