### ISSUE TITLE
Версии библиотек

### ISSUE THREAD

**Issue by serg-74** [vvip-68/GyverMatrixWiFi#6]
Здравствуйте.
При попытке повторить устройство столкнулся с проблемой: работает только первый светодиод (выбрана плата LOLIN(WEMOS) D1 R2 & mini, если выбираю плату WeMos D1 R1 - то работает только первых 63 светодиода.
Менеджер плат ESP8266 версии 2.5.0
Версия платформы Arduino 1.6.10 и 1.8.9
Версия библиотеки FastLEd 3.2.9
Проверено на 2-х разных платах. Плеер, кнопку и датчик освещенности не использую.
Подскажите Ваши версии: платформы, менеджера плат, выбранный тип платы, версии используемых библиотек.
Спасибо.

**Comment by vvip-68** [comment]
Для тех, кто сам не разобрался: версия библиотеки поддержки плат ESP8266 должна быть 2.5.2 - только с этой версией работает обновленная FastLED 3.2.9
