### ISSUE TITLE
Выложить исходники Android/iOs приложений

### ISSUE THREAD

**Issue by khvalov** [vvip-68/GyverMatrixWiFi#8]
День добрый. 
Есть ли возможность выложить исходники Android/iOs приложений для улучшения их функционала ?

**Comment by vvip-68** [comment]
Для андроида исходник есть в проектe - папка Android, файл GyverMatrixWiFi.aia - открывайте его в Thunkable и правьте как нужно. Для iOS, насколько я понимаю программы в природе не существует. Но вы можете сами написать ее под себя.
