### ISSUE TITLE
dawnColorSat2 causes a section type conflict with __c

### ISSUE THREAD

**Issue by AndrewVlz** [vvip-68/GyverMatrixWiFi#9]
Добрый день!

Вынужден переоткрыть ранее закрытый issue.

Получил такую же ошибку при компиляции Вашей программы.

"dawnColorSat2 causes a section type conflict with __c"

скетч effects.ino.

При этом dawnColorSat с таким же содержимым ошибок не вызывает.

Настройки компиляции, версия Arduino IDE прилагаются.

В чем может быть проблема?
![65448905-8873a980-de42-11e9-8729-e5d348c07ec1 1](https://user-images.githubusercontent.com/55710934/65877347-1c3dfc00-e394-11e9-9a29-6c9a444ac37f.png)
![65448912-8dd0f400-de42-11e9-96cf-9f365826a892 1](https://user-images.githubusercontent.com/55710934/65877361-2829be00-e394-11e9-96f3-8791b5bf119b.png)

Спасибо!

**Comment by vvip-68** [comment]
Попробуйте для начала поставить последнюю версию ArduinoIDE - 1.8.10 и попробовать скомпилить скетч в ней.

**Comment by AndrewVlz** [comment]
Спасибо за совет!

Установил Arduino IDE 1.8.10.

1. clock.ino - для строки " if (!timeServerIP.isSet()) timeServerIP.fromString(F("192.36.143.130"));  // Один из ru.pool.ntp.org // 195.3.254.2" выдается ошибка:

clock:82:21: error: 'class IPAddress' has no member named 'isSet'.

Закомментировал данную строку (кстати, компилятор "ругался" на неё и в предыдущей версии).

2. effects.ino - вновь та же ошибка:

dawnColorSat2 causes a section type conflict with __c.

В настройках компиляции перебрал оба NodeMCU и все четыре WeMos - ошибка та же.

В чем же проблема?

Я приложил сообщения об ошибках в текстовом файле - возможно, это поможет найти решение.
[Errors.txt](https://github.com/vvip-68/GyverMatrixWiFi/files/3677666/Errors.txt)

**Comment by vvip-68** [comment]
Проблема в том, что у вас старая версия ядра ESP8266 (скорее всего 2.4.x вместо рекомендованной 2.5.2) и вы совсем не читаете инструкции к проекту...
